apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: observability
data:
  logging.xml: |
    <clickhouse>
      <logger>
        <level>information</level>
        <console>true</console>
      </logger>
      <timezone>Europe/Berlin</timezone>
      <tmp_path>/tmp/clickhouse/</tmp_path>
    </clickhouse>
  init.sql: |
    CREATE DATABASE IF NOT EXISTS otel;
    CREATE DATABASE IF NOT EXISTS langfuse;