---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  metrics:
    enable: true
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-ingress
spec:
  type: ingress
  replicas: 2
  proxyClass: default
