---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: the-node
spec:
  parentRefs:
    - name: agentgateway-proxy
      namespace: agentgateway-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v1/chat/completions
    backendRefs:
    - name: the-node-llm
      namespace: agentgateway-system
      group: agentgateway.dev
      kind: AgentgatewayBackend
  - matches:
    - path:
        type: PathPrefix
        value: /v1/embeddings
    backendRefs:
    - name: the-node-embeddings
      namespace: agentgateway-system
      group: agentgateway.dev
      kind: AgentgatewayBackend
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: the-node-llm
spec:
  ai:
    provider:
      openai:
        model: unsloth/gemma-4-12B-it-GGUF
      host: the-node.gateway.svc.cluster.local
      port: 8000
      path: /v1/chat/completions
  policies:
    auth:
      secretRef:
       name: the-nodeai
    modelAliases: 
      the-node/gemma4-12b: unsloth/gemma-4-12B-it-GGUF
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: the-node-embeddings
spec:
  ai:
    provider:
      custom:
        model: google/embeddinggemma-300m
        formats:
        - type: Embeddings
          path: /v1/embeddings
      host: the-node.gateway.svc.cluster.local
      port: 8001
  policies:
    modelAliases: 
      the-node/embeddinggemma-300m: google/embeddinggemma-300m