---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway-embeddings
spec:
  gatewayClassName: agentgateway
  infrastructure:
    parametersRef:
      name: agentgateway-embeddings-config
      group: agentgateway.dev
      kind: AgentgatewayParameters
  listeners:
  - protocol: HTTP
    port: 8000
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agentgateway-embeddings-config
spec:
  service:
    spec:
      type: ClusterIP
  deployment:
    spec:
      replicas: 2
