apiVersion: ENC[AES256_GCM,data:Kgo=,iv:9CxHjFmeBhEDHO3gJx6PJDxq4eH+6Phe/9d8M/89QkU=,tag:boCmKVuYWyKgCKW/v1Mnkw==,type:str]
data:
    Authorization: ENC[AES256_GCM,data:EJiCfn2gMovxaJj0ae0dB87eHoxRZmL4ATGQVV2BDHtoP7F+85RZIZDKuVk=,iv:QqzYW+5oGTpVfvMJ3iy4BxHOJfN6ZIUGRqUZws1jL/U=,tag:Tt59YhQ7MtFxWqO+/01BCQ==,type:str]
kind: ENC[AES256_GCM,data:Jt8lidK/,iv:zzYU61jdX9t+jyJcF6aHQch/l6oR4y4Y67vloz6Mikc=,tag:gWlVh1ccspTw1OILxVM/VQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Tr6Jq8gxamg=,iv:d+jxEskl/ZSOH3lOJhIWQMKWSWEiky2DBlSqH2yBhe8=,tag:0HriamRom8jZtkYyV4laUQ==,type:str]
    namespace: ENC[AES256_GCM,data:U3Yl04isssQBFx0sE5fJWIkFSA==,iv:dc8KZf9e9zSfGkxgRmcAR+fPlSw5RydHYooQw855Emg=,tag:qNNl6btDK6lyR+mnKD5MRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTEN6T0tTVm1rcGxZRSt5
            Y25Xc0h2djNpWFlReks4ZHZ2QXAxNkc4bFhBCmhXQlJJT2Jab1FqVlYvTU9VdnlM
            NFJ1WXZpWVNWZWo2enRZZTV3bVBTSmsKLS0tIEVlRGdnQnlPMFpCckxaQ2xsVC9q
            akFYUjVZQUZXa2ovVnJNSzE4KzRYUjAKkzVdTeOmG4PXZB65L+boNSJ/CRc0kS7y
            UNDmjP6Mw5CmYSDy6Ti0mVPJndz54vqwG07VmU8UqhvcHImKhRcvXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13u5hjfgzvxkfsleme5vfz9drnk9jevevw56sulg8z9q5zepe6gjqw7x06d
    lastmodified: "2026-08-09T16:14:49Z"
    mac: ENC[AES256_GCM,data:X8K69nlyUjo6uSnpJp+4TVSHsL7V6w1XDU54MkwOjJ3KISl3H5cvwcOPQyfr0bAIB9clvDF+SVS4ZGgRwt7X3jj0M7c9GMYdMFrgYDnidu9Qgu13xoNmtqmskAAJLWAkJRgk2LqpecPMnM7GybPY6TDxmg8gcfF58JtljGkmhI4=,iv:K8mB4c5w2KLQUK9NrTvffeVgfnhfGr/15a2zyjwiTKs=,tag:AJFb2SuBlMTGFZypWGiHKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
