apiVersion: ENC[AES256_GCM,data:d6o=,iv:Dnvorb7rKj0SBqyfkVhXej+t3/6iL1/FgHFCzLPPSDY=,tag:qZ4woH3YhP4ZTmU2II5RUA==,type:str]
data:
    Authorization: ENC[AES256_GCM,data:DW+jJHdlm1UJtZu2WPgW4KDmQI7frRCZfT65taKv7cLqZOUVFlTb+0dhMEY=,iv:sc8hNNN0B7Ly0LK0Y0doZ4OpH7z1lr175DT15/nqL64=,tag:gxDSGceG+NVgF1UOG6X63Q==,type:str]
kind: ENC[AES256_GCM,data:SDE0O3fL,iv:BWygH/5j3vccDVgqgqPcibhqA5CJWLlOcafxDGJAQoo=,tag:KYq322zTtDfjwcrLXFqCQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dWjGE6caNvs=,iv:0TbpJ77QHgklGBylfyGbEHKW/oBHY47HajRBItOgQLs=,tag:lOnIDxaPNIo513uwypKw0w==,type:str]
    namespace: ENC[AES256_GCM,data:F1y2sbwtjWFNOxrMEaAGSVSRDQ==,iv:B4tOmjlmmLoj7WjluQVKCOgHojlJ4rXdMQsNKrECIh4=,tag:S51VSPEpiMQVe/lLiB3xTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb091Z3VGajdsajVFRnpX
            cUJwUGp0WWEzazV2SzgrSGY4YmhKd1h6TjJVCk1wdGJWRkx0cGpRYzVtam14L3Ex
            ek1mNHRhN2F6OXdFR0NFZ0ZRWU9CcU0KLS0tIHRrSk5yaXlEcVQ2TEhCcFY2RmxP
            aUdBcEUwSXBMMEp4R09rS2MvcUZKNmsKsIZCUoj6MwoagC55WidB6ED32z6aKjEv
            +nqJAimwtXu75AI37/5cQOXpVqQUHSELmhg/YGtlVJpgebvK9rHIQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13u5hjfgzvxkfsleme5vfz9drnk9jevevw56sulg8z9q5zepe6gjqw7x06d
    lastmodified: "2026-08-29T12:31:19Z"
    mac: ENC[AES256_GCM,data:TvideEafEwcv2R9Jb05Z5eTmnIyLir34r6/MMKt56J0Ii+ATW2mx6RblgrqPEv6QUZkiQjLLA0O97a/cLW+mmBDXS/TqY/hUyWeQTYA9x09rfYZxAo4BLESBS8CsasvMUi9Fl3Q5EYLA9XRoO5+tx0LVwQZGmCmP5n7SXqgQCr4=,iv:61QhJ81JZf6Wau0lJeMqQbgKRZdBeGm4NUNCM4cXpgI=,tag:aaWAlwUbsTqieMAqXp1Wbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
