apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
- allow-from-n8n.yaml
- allow-from-contenthub.yaml
- allow-prometheus-scraping.yaml
- namespace.yaml

components:
- ../../../components/security-baseline