---
# helm upgrade --install -n postgres postgres oci://registry-1.docker.io/cloudpirates/postgres --version 0.20.2 --values clusters/homelab/namespaces/databases/postgres/values.yaml
fullnameOverride: postgres
image:
  repository: pgvector/pgvector
  tag: 0.8.6-pg18-trixie
replicaCount: 1
resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 256Mi
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
  size: 20Gi
  storageClass: local-path
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    selector:
      release: kube-prometheus
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - local-ssd
